export const INITIALIZE = "INITIALIZE";

export const LOAD = "LOAD";
export const SAVE = "SAVE";
export const UPDATE = "SAVE";
export const LOAD_STATIONS = "LOAD_STATIONS";
export const STATIONS_LOADED = "STATIONS_LOADED";

export const FOUND = "FOUND";
export const MAYBE_LOST = "MAYBE_LOST";
export const PROBABLY_LOST = "PROBABLY_LOST";
export const LOST = "LOST";

export const QUERY_ALL = "QUERY_ALL";
export const QUERY_NECESSARY = "QUERY_NECESSARY";
export const QUERY_STATION = "QUERY_STATION";
export const TRY_STATION = "TRY_STATION";
export const TRY_STATION_ONCE = "TRY_STATION_ONCE";
export const STATION_REPLY = "STATION_REPLY";

export const STATION_PORTAL_ERROR = "STATION_PORTAL_ERROR";
export const STATION_PORTAL_REPLY = "STATION_PORTAL_REPLY";

export const AUTHENTICATED = "AUTHENTICATED";

export const REFRESH = "REFRESH";

export const SCAN_FOR_STATIONS = "SCAN_FOR_STATIONS";

export const UPLOAD_ALL = "UPLOAD_ALL";
export const UPLOAD_STATION = "UPLOAD_STATION";

export const DOWNLOAD_ALL = "DOWNLOAD_ALL";
export const DOWNLOAD_STATION = "DOWNLOAD_STATION";

export const FIRMWARE_REFRESH = "FIRMWARE_REFRESH";

// Media

export const AUDIO_RECORD = "AUDIO_RECORD";
export const AUDIO_PAUSE = "AUDIO_PAUSE";
export const AUDIO_RESUME = "AUDIO_RESUME";
export const AUDIO_STOP = "AUDIO_STOP";

export const TAKE_PICTURE = "TAKE_PICTURE";
export const FIND_PICTURE = "FIND_PICTURE";
export const SAVE_PICTURE = "SAVE_PICTURE";
export const LOAD_PICTURES = "LOAD_PICTURES";

// Deploy

export const RENAME_STATION = "RENAME_STATION";
export const CONFIGURE_STATION_NETWORK = "CONFIGURE_STATION_NETWORK";
export const CONFIGURE_STATION_SCHEDULES = "CONFIGURE_STATION_SCHEDULES";
export const STATION_LOCATION = "STATION_LOCATION";
export const SCAN_STATION_NETWORKS = "SCAN_STATION_NETWORKS";

export const UPDATE_NOTES_FORM = "UPDATE_NOTES_FORM";
export const DEPLOY_STATION = "DEPLOY_STATION";
export const END_STATION_DEPLOYMENT = "END_STATION_DEPLOYMENT";
export const SAVE_NOTES = "SAVE_NOTES";

// Portal

export const UPDATE_PORTAL = "UPDATE_PORTAL";

// Calibration

export const CALIBRATE_SENSOR = "CALIBRATE_SENSOR";
export const CLEAR_SENSOR_CALIBRATION = "CLEAR_SENSOR_CALIBRATION";

export const LOAD_SETTINGS = "LOAD_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";

export const LOAD_ACCOUNTS = "LOAD_ACCOUNTS";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const LOGOUT_ACCOUNTS = "LOGOUT_ACCOUNTS";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";

// Notifications

export const LOAD_NOTIFICATIONS = "LOAD_NOTIFICATIONS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const DISMISS_NOTIFICATION = "DISMISS_NOTIFICATION";
export const SATISFY_NOTIFICATION = "SATISFY_NOTIFICATION";
