export const INITIALIZE = "INITIALIZE";

export const LOAD = "LOAD";
export const SAVE = "SAVE";
export const UPDATE = "SAVE";
export const STATIONS_LOADED = "STATIONS_LOADED";

export const FOUND = "FOUND";
export const LOST = "LOST";

export const QUERY_ALL = "QUERY_ALL";
export const QUERY_NECESSARY = "QUERY_NECESSARY";
export const QUERY_STATION = "QUERY_STATION";
export const STATION_REPLY = "STATION_REPLY";

export const STATION_PORTAL_ERROR = "STATION_PORTAL_ERROR";
export const STATION_PORTAL_REPLY = "STATION_PORTAL_REPLY";

export const AUTHENTICATED = "AUTHENTICATED";

export const REFRESH = "REFRESH";

export const UPLOAD_ALL = "UPLOAD_ALL";
export const UPLOAD_STATION = "UPLOAD_STATION";

export const DOWNLOAD_ALL = "DOWNLOAD_ALL";
export const DOWNLOAD_STATION = "DOWNLOAD_STATION";

export const FIRMWARE_REFRESH = "FIRMWARE_REFRESH";

// Media

export const AUDIO_RECORD = "AUDIO_RECORD";
export const AUDIO_PAUSE = "AUDIO_PAUSE";
export const AUDIO_RESUME = "AUDIO_RESUME";
export const AUDIO_STOP = "AUDIO_STOP";

export const TAKE_PICTURE = "TAKE_PICTURE";
export const FIND_PICTURE = "FIND_PICTURE";
export const SAVE_PICTURE = "SAVE_PICTURE";
export const LOAD_PICTURES = "LOAD_PICTURES";

// Deploy

export const RENAME_STATION = "RENAME_STATION";
export const CONFIGURE_STATION_NETWORK = "CONFIGURE_STATION_NETWORK";
export const CONFIGURE_STATION_SCHEDUES = "CONFIGURE_STATION_SCHEDUES";
export const STATION_LOCATION = "STATION_LOCATION";

export const UPDATE_NOTES_FORM = "UPDATE_NOTES_FORM";
export const DEPLOY_STATION = "DEPLOY_STATION";

// Portal

export const UPDATE_PORTAL = "UPDATE_PORTAL";
