export const LOAD = "LOAD";
export const SAVE = "SAVE";
export const UPDATE = "SAVE";
export const STATIONS_LOADED = "STATIONS_LOADED";

export const FOUND = "FOUND";
export const LOST = "LOST";

export const QUERY_ALL = "QUERY_ALL";
export const QUERY_NECESSARY = "QUERY_NECESSARY";
export const QUERY_STATION = "QUERY_STATION";
export const STATION_REPLY = "STATION_REPLY";

export const STATION_PORTAL_ERROR = "STATION_PORTAL_ERROR";
export const STATION_PORTAL_REPLY = "STATION_PORTAL_REPLY";

export const AUTHENTICATED = "AUTHENTICATED";

export const REFRESH = "REFRESH";

export const UPLOAD_UPLOAD = "UPLOAD_UPLOAD";
export const UPLOAD_STATION = "UPLOAD_STATION";
export const UPLOAD_COMPLETED = "UPLOAD_COMPLETED";

export const DOWNLOAD_ALL = "DOWNLOAD_ALL";
export const DOWNLOAD_STATION = "DOWNLOAD_STATION";
export const DOWNLOAD_COMPLETED = "DOWNLOAD_COMPLETED";
