#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACM | sed 's| |\\ |g' | grep -E '\.(js|jsx)$')

[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0

