#+TITLE:  README for app

* Developers
** iOS / XCode
   Opening in XCode, use xcworkspace, otherwise you'll get build errors regarding missing frameworks.

** Apple M1 Notes

Tons of thoughts to follow that could use some organization.

Running ns doctor ios revealed a few issues, the commands I used to resolve
them are below:

#+BEGIN_SRC sh
   sudo gem install -n /usr/local/bin xcodeproj
   sudo gem install -n /usr/local/bin cocoapods
   pip install six
#+END_SRC

When running ns prepare ios, an error occured in Ruby related to ffi, and this
command resolved that:

#+BEGIN_SRC sh
   gem install --user-install ffi -- --enable-libffi-alloc
#+END_SRC

** Migrations
*** New Migrations

There's is a tool in the repository to create a new repository and can be run like so:

#+BEGIN_SRC sh
tools/mkm.sh title_of_migration
#+END_SRC

Where `title_of_migration` is a short description of the
change. After running that there will be a new migration file and
the index.js will be updated to include that migration in future
runs.

Some caveats:

1) The class name in the generated migration will use the title_of_migration
casing and should be updated to reflect our naming convention. I hope to fix
this eventually.

2) If the app is running under the debugger then after running that command the
app will reload and run your blank/new migration, so be careful of that. I'm
still trying to think of a good solution to this.
