platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      # Solves signing errors that come from CocoaPods. If you see an error
      # about self signed chain, you need to double check the trust settings of
      # the certificates involved. At one point "Always Trust" was allowed, no
      # longer true!
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"

      # https://github.com/facebook/react-native/issues/36763
      config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO' 
    end
  end
end
